Rename autogen.sh to bootstrap. Move auxiliary scripts into cfg/. Correction of GUI toolkit test in configure.in. General autoconf/automake update.

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -1,5 +1,5 @@
 #! /bin/sh
-
+# **************************************************************************
 # Regenerate all files which are constructed by the autoconf, automake
 # and libtool tool-chain. Note: only developers should need to use
 # this script.
@@ -7,12 +7,13 @@
 # Authors:
 #   Morten Eriksen <mortene@sim.no>
 #   Lars J. Aas <larsa@sim.no>
-#   Ralph Levien (original autogen.sh picked up from Gnome source archive).
 
-directory=`echo "$0" | sed -e 's/[^\/]*$//g'`;
-cd $directory
-if ! test -f ./autogen.sh; then
-  echo "unexpected problem with your shell - bailing out"
+wd=`echo "$0" | sed 's,[^/]*$,,g'`
+me=`echo "$0" | sed 's,.*/,,g'`
+
+cd $wd
+if test ! -f ./$me; then
+  echo >&2 "$me: error: unexpected problem with your shell - bailing out"
   exit 1
 fi
 
@@ -20,7 +21,7 @@ AUTOCONF_VER=2.49b    # Autoconf from CVS
 AUTOMAKE_VER=1.4a     # Automake from CVS
 LIBTOOL_VER=1.3.5
 
-MACRODIR=../conf-macros-CVS
+# MACRODIR=../conf-macros-CVS
 DIE=false
 
 if test "$1" = "--clean"; then
@@ -82,54 +83,19 @@ if test -z "`libtool --version | grep \" $LIBTOOL_VER \" 2> /dev/null`"; then
     DIE=true
 fi
 
-# set $SUBPROJECTNAMES
-# num=1
-# for project in $SUBPROJECTS; do
-#   test -d $project || {
-#     echo "Could not find subdirectory '$project'."
-#     echo "It was probably added after you initially fetched $PROJECT."
-#     echo "To add the missing module, run 'cvs co $1' from the $PROJECT"
-#     echo "base directory."
-#     echo ""
-#     echo "To do a completely fresh cvs checkout of the whole $PROJECT module,"
-#     echo "(if all else fails), remove $PROJECT and run:"
-#     echo ""
-#     echo "  cvs -z3 -d :pserver:cvs@cvs.sim.no:/export/cvsroot co -P $PROJECT"
-#     echo ""
-#     DIE=true
-#   }
-#   num=`expr $num + 1`
-#   shift
-# done
+${DIE=false} && echo "" && echo >&2 "$me: error: aborting..." && exit 1
 
-$DIE && exit 1
+# **************************************************************************
 
-# AG_CRUNCH
-echo "Running aclocal (generating aclocal.m4)..."
-aclocal -I $MACRODIR
+echo "Running aclocal..."
+aclocal # -I $MACRODIR
 
-echo "Running autoheader (generating config.h.in)..."
-autoheader
+echo "Running autoheader..."
+( autoheader 3>&1 1>&2 2>&3 | grep -v 'is unchanged$' ) 3>&1 1>&2 2>&3
 
-echo "Running automake (generating the Makefile.in files)..."
-echo "[ignore any \"directory should not contain '/'\" warning]"
+echo "Running automake..."
 automake $AUTOMAKE_ADD
 
-AMBUGFIXES=`find . \( -name Makefile.in.diff \) | egrep -v '^\./(data|examples|ivexamples)'`
-
-fixmsg=0
-for bugfix in $AMBUGFIXES; do
-  if test $fixmsg -eq 0; then
-    echo "[correcting automake bugs]"
-    fixmsg=1
-  fi
-  patch -p0 < $bugfix
-done
-
-echo "Running autoconf (generating ./configure)..."
+echo "Running autoconf..."
 autoconf
-
-echo
-echo "Done: Now run './configure' and 'make install' to build $PROJECT."
-echo
 
