detect and explain the "duplicate .cfg-file" problem

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1256,11 +1256,32 @@ fi
 # **************************************************************************
 # Search and set up necessary stuff to use the GUI library.
 
+files=0
+for file in ../so*-*.cfg; do
+  files=`expr $files + 1`
+done
+if test $files -gt 1; then
+  rm -f ../so*-*.cfg
+  { { echo "$as_me:1265: error:
+  The configure script will now abort because the configure directory was
+  not clean from configuring/building with multiple --with-alternate options
+  without cleaning out the directory in-between.  The problematic duplicate
+  config files has been removed.  Please repeat the configure command -
+  you will get past this point on the next run.  Sorry for the inconvenience." >&5
+echo "$as_me: error:
+  The configure script will now abort because the configure directory was
+  not clean from configuring/building with multiple --with-alternate options
+  without cleaning out the directory in-between.  The problematic duplicate
+  config files has been removed.  Please repeat the configure command -
+  you will get past this point on the next run.  Sorry for the inconvenience." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
 sim_ac_configfile=../so*-*.cfg
 if test -f $sim_ac_configfile; then
   . $sim_ac_configfile;
 else
-  { { echo "$as_me:1263: error: found no config file in .." >&5
+  { { echo "$as_me:1284: error: found no config file in .." >&5
 echo "$as_me: error: found no config file in .." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -1374,7 +1395,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:1377: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:1398: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -1547,7 +1568,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:1550: error: ambiguous option: $1
+    { { echo "$as_me:1571: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1566,7 +1587,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:1569: error: unrecognized option: $1
+  -*) { { echo "$as_me:1590: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1618,7 +1639,7 @@ do
   "materials/tropical/Makefile" ) CONFIG_FILES="$CONFIG_FILES materials/tropical/Makefile" ;;
   "materials/winter/Makefile" ) CONFIG_FILES="$CONFIG_FILES materials/winter/Makefile" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
-  *) { { echo "$as_me:1621: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:1642: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -1845,7 +1866,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:1848: creating $ac_file" >&5
+    { echo "$as_me:1869: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -1863,7 +1884,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:1866: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:1887: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -1876,7 +1897,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:1879: error: cannot find input file: $f" >&5
+           { { echo "$as_me:1900: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -1937,7 +1958,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:1940: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:1961: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -1948,7 +1969,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:1951: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:1972: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -1961,7 +1982,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:1964: error: cannot find input file: $f" >&5
+           { { echo "$as_me:1985: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -2078,7 +2099,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:2081: $ac_file is unchanged" >&5
+      { echo "$as_me:2102: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
